# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_VIDEO_MA35D1_CAMERA)       += ma35d1-ccap.o
obj-$(CONFIG_VIDEO_MA35D0_CAMERA)       += ma35d0-ccap.o
obj-$(CONFIG_VIDEO_MA35H0_CAMERA)       += ma35h0-ccap.o
