# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_CLK_MA35D1) += clk-ma35d1.o
obj-$(CONFIG_CLK_MA35D1) += clk-ma35d1-divider.o
obj-$(CONFIG_CLK_MA35D1) += clk-ma35d1-pll.o
obj-$(CONFIG_ARCH_MA35D1) += clk-ma35d1.o clkdivider-ma35d1.o clk-ma35d1-pll.o
