# SPDX-License-Identifier: GPL-2.0-only

ifeq ($(CONFIG_CRYPTO_DEV_NUVOTON_MA35),y)
	obj-y += ma35-crypto.o
	obj-y += ma35-aes.o
	obj-y += ma35-prng.o
	obj-y += ma35-sha.o
	obj-y += ma35-ecc.o
	obj-y += ma35-rsa.o
	obj-y += ma35-crypto-optee.o
	obj-y += ma35-aes-optee.o
	obj-y += ma35-sha-optee.o
	obj-y += ma35-ecc-optee.o
	obj-y += ma35-rsa-optee.o
endif
